[Previewer]
IdlePlugin = Skyrim.esm
IdleRef = 0x000F3A99
IdleTime = 1.0


;; working
; Prayer 				- 0x000AF886 (~2s)
; IdleStaticPoseA		- 0x000D8262
; IdleT02AscendFemale 	- 0x000F3A99

;; unreliable
; 0x0002E52A 		- IdleWarmHands
; IdleMagic_01 		- 0x00075CB8 (requires equipped hand, becomes combat stance)
; IdleBook_Reading 	- 0x000BB052 (requires equipped hand)
; IdlePray 			- 0x0006F300 (requires equipped hand)
; IdleLookFar		- 0x00075C62 (requires equipped hand)

;; doesn't play
; RF_SeriousInterested	- 0x00003DCA
; IdleFluteStart - 0x00096F8C
; IdleWave	- 0x0003EA32

;; NOTES:
;; - most idles require Serana to have something in hands first.


[UpdateProperties]
bReadIni = true
;; 'SFF_MentalModelExtender'
bHasAskedCloseFollow = false
bHasAskedWalkBeside = true
bHasSetHome = false
bHasGivenHorse = false